const castDesc: string = "The cast are made up of the actors, singers, and dancers who perform on stage for the show. The cast are charged with the power to make the audience laugh, cheer, and lose control of their bowels every night. Being a member of cast requires a massive commitment, but is also arguably the most rewarding and exciting thing that you will ever do! The wonderful thing about revue is to be in cast NO EXPERIENCE IS REQUIRED! All we need from you is your dedication, enthusiasm, and luurve.";

const techDesc: string = `The Tech team construct the props and the sets for the show, from massive spinning fans, to doors and giant pieces of a monopoly set. During the show Techies operate lights and sound, run around like cockroaches setting the stage and play with the fog machine. If you have any experience with lighting, sound, set construction and related skills you'd be particularly welcome. But don't fret; if you've never done this before, we'll teach you all the skills you need.`;

const bandDesc: string = `The band are the masters of sound and music. As a member you will be part of the atmosphere and intrigue surrounding dances and skits. The band is also given time to shine in the illustrious band number - a highlight of any revue. Band puts in a dozen or so rehearsals and the four performance nights in session 2. Outside of that, the band is always looking for ways to avoid work, chill, and jam the night away. Bring your own instrument and all the musical talent you can muster!`;

const scriptsDesc: string = `The scripts team is home to the writers, the visionaries, the loud, the quiet, the offensive, the politically correct, the good, the bad, and the directors. And of course, YOU! The scripts team pump the show full of goodness in the form of comedy. We play games, talk loudly, brainstorm, discuss ideas, and when the time is write, we right material for the show! Scripts is a network and community, a giant mish mash of people and ideas from which amazing things always emerge.`;

const designDesc: string = `The design team are responsible for the look and feel of CSE Revue's many visual expressions including the website, T-shirts, stage set, newsletters, program and much more. The design team is a highly creative, dynamic group requiring time and dedication. You don't need prior skills or experience, so whether you like drawing, painting, sketching, cartoons or just seeing your ideas make it to the public, the Design team is the place to be seen.`;

const markDesc: string = "The marketing team is responsible for promoting CSE Revue to the wider university and Sydney community. Whether it's keeping our Facebook page up to date or filming and editing promotional Instagram reels, if you have a passion for communication, creativity and social media, marketing is the perfect place for you.";

const eventsDesc: string = `Events is the FUN factory of CSE Revue! We make it so that everyone is incorporated in the ride of Revue, enjoys fun times and takes away an abundance of memories. The events team organise movie nights and karaokes, the pizza and the parties, meeting and greeting new people while making every event a raving success. If you want to come up with super-cool events to put on or you're just looking to make new friends, you'll fit right into this cosy little team.`;

const fohDesc: string = `Front of House (a.k.a FoH) is all about keeping the audience happy. FoH make sure they are entertained before the show begins, provide them with food and drink, give them a band to listen to and show them to their seats. FoH also attracts people with an eye for detail - the decorators among you will be responsible for the theatre decorations. And the big bonus? The chance to see the show for free. Yes, that's right, free!`;

const videosDesc: string = `The Videos team takes ideas and scripts that are too hard to do on stage (or can be done much better through a lens) and uses professional equipment to make them come to life on the screen. If you're a budding cinematographer, 3D animator or if you've just seen far too many movies, we'd love to have you on board. Everyone, regardless of skill level, is welcome to join us in creating something that will get us and our audiences giggling.`;

const hospoDesc: string = `Hospitality is all about food and health! Delicious, life nurturing food and general health. As a member of the kind hospo team, you'll be looking after the cast and crew by assisting a team to cook for forty humans! hahaha, just kidding. Try a hundred and forty. Don't think you'll need cooking talents in any sense; all we need is a few of your hours in the evening, whether you're going to operate the rice cooker or just learn a new recipe.`;

export { castDesc, techDesc, bandDesc, scriptsDesc, designDesc, markDesc, eventsDesc, fohDesc, videosDesc, hospoDesc };